#  Frontend Service  
apiVersion: v1
kind: Service
metadata:
  name: taskmanagement-frontend-service
spec:
  selector:
    app: taskmanagement-frontend 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
  type: LoadBalancer 
